# Generated by Django 5.0.6 on 2024-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmenwork_app', '0006_banner_image_alter_banner_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeatherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('garments', 'Leather Garments'), ('bags', 'Leather Bags'), ('belts', 'Leather Belts'), ('small_goods', 'Small Leather Goods')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
