# Generated by Django 5.0.6 on 2024-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmenwork_app', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
