# Generated by Django 5.0.6 on 2024-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmenwork_app', '0012_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
